import { Router, Request, Response } from "express";
import { z } from "zod";
import { execute, query, queryOne } from "../config/database";
import { authenticateToken } from "../middleware/authMiddleware";
import { UserModel } from "../models/User";
import { generateSnowflakeId } from "../utils/snowflake";
const router: Router = Router(); router.use(authenticateToken);
const IdParamSchema = z.string().min(1);
const CreateApplicationSchema = z.object({ title: z.string().min(1).max(200), client_type: z.number().int().min(1).max(2).optional().default(1), status: z.number().int().min(0).max(1).optional().default(1), schema: z.any().optional() });
const UpdateApplicationSchema = z.object({ title: z.string().min(1).max(200).optional(), client_type: z.number().int().min(1).max(2).optional(), status: z.number().int().min(0).max(1).optional(), schema: z.any().optional(), starred: z.boolean().optional() });
function defaultSchema(clientType: number): Record<string, unknown> { const pageSize = clientType === 2 ? { name: "", width: 375, height: 667 } : { name: "", width: 1920, height: 1080 }; return { pages: { "/": { title: "首页", path: "/", config: { bgColor: "", bgImage: "", keepAlive: false, pageSize }, blocks: [] } }, models: [], actions: { fetch: { name: "接口请求", apis: [] }, dialog: { name: "对话框", handlers: [] } } }; }
function listItem(row: Record<string, unknown>) { return { id: row.id, title: row.title, status: Number(row.status), client_type: Number(row.client_type), starred: Boolean(row.starred), lastUpdated: row.updated_at, created_at: row.created_at, updated_at: row.updated_at }; }
function parseSchema(raw: string, clientType: number) { try { const value = JSON.parse(raw || "{}"); if (value?.pages) return value; } catch {} return defaultSchema(clientType); }
router.get("/", async (req: Request, res: Response) => { try { let sql = "SELECT * FROM applications WHERE owner_id = ?", params: unknown[] = [req.userId!]; if (req.query.status === "enable") sql += " AND status = 1"; if (req.query.status === "disable") sql += " AND status = 0"; const rows = await query<Record<string, unknown>[]>(`${sql} ORDER BY updated_at DESC`, params), items = rows.map(listItem); res.json({ success: true, data: { items, total: items.length }, message: "获取应用列表成功" }); } catch (error) { console.error("applications list error:", error); res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.get("/:id", async (req, res) => { try { const id = IdParamSchema.parse(req.params.id), row = await queryOne<Record<string, unknown>>("SELECT * FROM applications WHERE id = ? AND owner_id = ?", [id, req.userId!]); if (!row) return res.status(404).json({ success: false, error: "应用不存在" }); const clientType = Number(row.client_type) || 1; res.json({ success: true, data: { ...listItem(row), schema: parseSchema(String(row.schema_json), clientType) }, message: "获取应用成功" }); } catch (error) { if (error instanceof z.ZodError) return res.status(400).json({ success: false, error: "无效的应用 ID" }); res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.post("/", async (req, res) => { try { const body = CreateApplicationSchema.parse(req.body), owner = await UserModel.findByPk(req.userId!); if (!owner?.is_active) return res.status(401).json({ success: false, error: "登录已失效，请重新登录" }); const id = generateSnowflakeId(), now = new Date().toISOString(), schema = JSON.stringify(body.schema ?? defaultSchema(body.client_type)); await execute("INSERT INTO applications (id, title, status, client_type, schema_json, starred, owner_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)", [id, body.title, body.status, body.client_type, schema, req.userId!, now, now]); const row = (await queryOne<Record<string, unknown>>("SELECT * FROM applications WHERE id = ?", [id]))!; res.status(201).json({ success: true, data: { ...listItem(row), schema: JSON.parse(String(row.schema_json)) }, message: "创建应用成功" }); } catch (error) { if (error instanceof z.ZodError) return res.status(400).json({ success: false, error: "数据验证失败", details: error.errors }); console.error("applications create error:", error); res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.put("/:id", async (req, res) => { try { const id = IdParamSchema.parse(req.params.id), body = UpdateApplicationSchema.parse(req.body), existing = await queryOne<Record<string, unknown>>("SELECT * FROM applications WHERE id = ? AND owner_id = ?", [id, req.userId!]); if (!existing) return res.status(404).json({ success: false, error: "应用不存在" }); await execute("UPDATE applications SET title = ?, status = ?, client_type = ?, schema_json = ?, starred = ?, updated_at = ? WHERE id = ? AND owner_id = ?", [body.title ?? existing.title, body.status ?? existing.status, body.client_type ?? existing.client_type, body.schema !== undefined ? JSON.stringify(body.schema) : existing.schema_json, body.starred !== undefined ? Number(body.starred) : Number(existing.starred), new Date().toISOString(), id, req.userId!]); const row = (await queryOne<Record<string, unknown>>("SELECT * FROM applications WHERE id = ?", [id]))!; res.json({ success: true, data: { ...listItem(row), schema: parseSchema(String(row.schema_json), Number(row.client_type) || 1) }, message: "更新应用成功" }); } catch (error) { if (error instanceof z.ZodError) return res.status(400).json({ success: false, error: "数据验证失败", details: error.errors }); res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.delete("/:id", async (req, res) => { try { const result = await execute("DELETE FROM applications WHERE id = ? AND owner_id = ?", [IdParamSchema.parse(req.params.id), req.userId!]); if (!result.affectedRows) return res.status(404).json({ success: false, error: "应用不存在" }); res.json({ success: true, data: null, message: "删除应用成功" }); } catch { res.status(500).json({ success: false, error: "服务器内部错误" }); } });
export default router;
