import { Request, Response, Router } from "express";
import { z } from "zod";
import { execute, query, queryOne } from "../config/database";
import { generateSnowflakeId } from "../utils/snowflake";
const router: Router = Router();
const PageSchema = z.object({ name: z.string().min(1).max(100), components: z.array(z.any()), settings: z.record(z.string(), z.any()).optional() });
function serialize(row: { components: string; settings?: string | null; [key: string]: unknown }) { return { ...row, components: JSON.parse(row.components || "[]"), settings: row.settings ? JSON.parse(row.settings) : undefined }; }
router.get("/pages", async (_req: Request, res: Response) => { try { const rows = await query<Array<{ components: string; settings?: string | null; [key: string]: unknown }>>("SELECT * FROM lowcode_pages ORDER BY created_at DESC"); const pages = rows.map(serialize); res.json({ success: true, data: pages, total: pages.length, message: "获取页面列表成功" }); } catch { res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.post("/pages", async (req: Request, res: Response) => { try { const data = PageSchema.parse(req.body), id = generateSnowflakeId(), now = new Date().toISOString(); await execute("INSERT INTO lowcode_pages (id, name, components, settings, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)", [id, data.name, JSON.stringify(data.components), data.settings ? JSON.stringify(data.settings) : null, now, now]); res.status(201).json({ success: true, data: { id, ...data, createdAt: new Date(now), updatedAt: new Date(now) }, message: "页面创建成功" }); } catch (error) { if (error instanceof z.ZodError) res.status(400).json({ success: false, error: "数据验证失败", details: error.errors }); else res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.put("/pages/:id", async (req: Request, res: Response) => { try { const existing = await queryOne<{ name: string; components: string; settings?: string | null }>("SELECT * FROM lowcode_pages WHERE id = ?", [req.params.id]); if (!existing) return res.status(404).json({ success: false, error: "页面不存在" }); const data = PageSchema.partial().parse(req.body), now = new Date().toISOString(); await execute("UPDATE lowcode_pages SET name = ?, components = ?, settings = ?, updated_at = ? WHERE id = ?", [data.name ?? existing.name, data.components !== undefined ? JSON.stringify(data.components) : existing.components, data.settings !== undefined ? JSON.stringify(data.settings) : existing.settings ?? null, now, req.params.id]); res.json({ success: true, data: serialize((await queryOne<any>("SELECT * FROM lowcode_pages WHERE id = ?", [req.params.id]))!), message: "页面更新成功" }); } catch (error) { if (error instanceof z.ZodError) res.status(400).json({ success: false, error: "数据验证失败", details: error.errors }); else res.status(500).json({ success: false, error: "服务器内部错误" }); } });
router.delete("/pages/:id", async (req: Request, res: Response) => { const result = await execute("DELETE FROM lowcode_pages WHERE id = ?", [req.params.id]); if (!result.affectedRows) return res.status(404).json({ success: false, error: "页面不存在" }); res.json({ success: true, message: "页面删除成功" }); });
export default router;
