import { execute, query, queryOne, withTransaction } from "../config/database";
import { generateSnowflakeId } from "../utils/snowflake";
import type { PagePublic, PageType } from "./Page";
export interface AppPageMenu { id: string; application_id: string; page_id: string; parent_id?: string | null; menu_title: string; menu_icon?: string | null; route_path?: string | null; permission?: string | null; sort_order: number; created_at: string; }
export interface MenuTreeNode { id: string; application_id: string; page_id?: string | null; parent_id?: string | null; menu_title: string; menu_icon?: string | null; route_path?: string | null; permission?: string | null; sort_order: number; isFolder: boolean; page?: Pick<PagePublic, "id" | "name" | "type" | "status"> | null; children: MenuTreeNode[]; }
function rowToMenu(row: AppPageMenu): AppPageMenu { return { ...row, parent_id: row.parent_id ?? null, menu_icon: row.menu_icon ?? null, route_path: row.route_path ?? null, permission: row.permission ?? null, sort_order: Number(row.sort_order) }; }
export class AppPageMenuModel {
 static async getMenuTree(applicationId: string): Promise<MenuTreeNode[]> { const rows = await query<Array<AppPageMenu & { page_name?: string; page_type?: string; page_status?: string }>>("SELECT m.*, p.name AS page_name, p.type AS page_type, p.status AS page_status FROM app_page_menus m LEFT JOIN pages p ON m.page_id = p.id WHERE m.application_id = ? ORDER BY m.sort_order ASC, m.created_at ASC", [applicationId]); const map = new Map<string, MenuTreeNode>(), roots: MenuTreeNode[] = []; for (const row of rows) { const pageId = row.page_id ?? null; map.set(row.id, { ...rowToMenu(row), page_id: pageId, isFolder: !pageId, page: pageId ? { id: pageId, name: row.page_name ?? "", type: (row.page_type ?? "visualization") as PageType, status: (row.page_status ?? "draft") as "draft" | "published" } : null, children: [] }); } for (const node of map.values()) { if (node.parent_id && map.has(node.parent_id)) map.get(node.parent_id)!.children.push(node); else roots.push(node); } return roots; }
 static async create(data: { application_id: string; page_id?: string | null; parent_id?: string | null; menu_title: string; menu_icon?: string; route_path?: string; permission?: string; sort_order?: number; }): Promise<AppPageMenu> { const next = data.sort_order ?? Number((await queryOne<{ next: number | string }>("SELECT COALESCE(MAX(sort_order), -1) + 1 AS next FROM app_page_menus WHERE application_id = ?", [data.application_id]))?.next ?? 0), id = generateSnowflakeId(); await execute("INSERT INTO app_page_menus (id, application_id, page_id, parent_id, menu_title, menu_icon, route_path, permission, sort_order, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [id, data.application_id, data.page_id ?? null, data.parent_id ?? null, data.menu_title, data.menu_icon ?? null, data.route_path ?? null, data.permission ?? null, next, new Date().toISOString()]); return rowToMenu((await queryOne<AppPageMenu>("SELECT * FROM app_page_menus WHERE id = ?", [id]))!); }
 static async update(id: string, data: { menu_title?: string; menu_icon?: string | null; route_path?: string | null; permission?: string | null; parent_id?: string | null; sort_order?: number; }): Promise<AppPageMenu | undefined> { const existing = await queryOne<AppPageMenu>("SELECT * FROM app_page_menus WHERE id = ?", [id]); if (!existing) return undefined; await execute("UPDATE app_page_menus SET menu_title = ?, menu_icon = ?, route_path = ?, permission = ?, parent_id = ?, sort_order = ? WHERE id = ?", [data.menu_title ?? existing.menu_title, data.menu_icon !== undefined ? data.menu_icon : existing.menu_icon ?? null, data.route_path !== undefined ? data.route_path : existing.route_path ?? null, data.permission !== undefined ? data.permission : existing.permission ?? null, data.parent_id !== undefined ? data.parent_id : existing.parent_id ?? null, data.sort_order ?? existing.sort_order, id]); return rowToMenu((await queryOne<AppPageMenu>("SELECT * FROM app_page_menus WHERE id = ?", [id]))!); }
 static async batchUpdateSort(items: Array<{ id: string; parent_id?: string | null; sort_order: number }>): Promise<void> { await withTransaction(async connection => { for (const item of items) await connection.execute("UPDATE app_page_menus SET parent_id = ?, sort_order = ? WHERE id = ?", [item.parent_id ?? null, item.sort_order, item.id]); }); }
 static async delete(id: string): Promise<boolean> { const children = await query<Array<{ id: string }>>("SELECT id FROM app_page_menus WHERE parent_id = ?", [id]); for (const child of children) await this.delete(child.id); return (await execute("DELETE FROM app_page_menus WHERE id = ?", [id])).affectedRows > 0; }
 static async isPageMounted(pageId: string): Promise<boolean> { return Boolean(await queryOne("SELECT 1 FROM app_page_menus WHERE page_id = ? LIMIT 1", [pageId])); }
 static async getMountedPageIds(applicationId: string): Promise<string[]> { return (await query<Array<{ page_id: string }>>("SELECT DISTINCT page_id FROM app_page_menus WHERE application_id = ? AND page_id IS NOT NULL", [applicationId])).map(row => row.page_id); }
}
export default AppPageMenuModel;
